const express = require('express')
const cors = require('cors')
const cookieParser = require('cookie-parser')
const dotenv = require('dotenv')
const morgan = require('morgan')
dotenv.config()
const passport = require('passport')
require('./passportSetup')
const authRoutes = require('./routes/auth.route')
const userRoutes = require('./routes/user.route')
const placeTypeRoutes = require('./routes/placeType.route')
const provinceRoutes = require('./routes/province.route')
const districtRoutes = require('./routes/district.route')
const placeRequestRoutes = require('./routes/placeRequest.route')
const imageRoutes = require('./routes/image.route')
const placeRoutes = require('./routes/place.route')
const reviewRoutes = require('./routes/review.route')
const saveRoutes = require('./routes/save.route')
const notiRoutes = require('./routes/notification.route')
const questionRoutes = require('./routes/question.route')
const dashboardRoutes = require('./routes/dashboard.route')

const app = express()
app.use(cookieParser())
app.use(cors({
    credentials: true,
    origin: ['http://localhost:5173', process.env.FRONTEND_URL]
}))
app.use(morgan('dev'))
app.use(express.json({ limit: '30mb' }))
app.use(express.urlencoded({ limit: '30mb', extended: true }))
app.use(passport.initialize())

app.use('/auth-api', authRoutes)
app.use('/user-api', userRoutes)
app.use('/place-type-api', placeTypeRoutes)
app.use('/province-api', provinceRoutes)
app.use('/district-api', districtRoutes)
app.use('/placeRequest-api', placeRequestRoutes)
app.use('/image-api', imageRoutes)
app.use('/place-api', placeRoutes)
app.use('/review-api', reviewRoutes)
app.use('/save-api', saveRoutes)
app.use('/noti-api', notiRoutes)
app.use('/question-api', questionRoutes)
app.use('/dashboard-api', dashboardRoutes)

const PORT = process.env.PORT || 5000
app.listen(PORT, () => {
    console.log(`Server is running on PORT ${PORT}`)
})